apiVersion: v2
name: weeklychecks
description: A Helm chart for Paylite Weeklychecks
type: application
version: 1.0.0
appVersion: 1.0.0
icon: https://cdn-icons-png.flaticon.com/512/1355/1355919.png
dependencies:
  - name: greet
    repository: "file://charts/greet"
    version: 1.0.0

  - name: calc
    repository: "file://charts/calc"
    version: 1.0.0
